In [1]:
# 构建简单的神经网络
%matplotlib inline
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [2]:
torch.__version__

'1.11.0+cu113'

In [3]:
# 决定用来训练的设备
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using {} device'.format(device))

Using cuda device


In [4]:
# 继承nn.Module实现模型
# 在__init__()方法初始化层
# 在forward()方法实现对输入的数据操作
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
            nn.ReLU()
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits


In [5]:
# 将模型移至GPU
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
)


In [6]:
# 将数据输入到模型，会自动执行forward()并做一些其他工作，不要直接调用forward()
# 使用softmax获取概率最大地类别
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
print(logits)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")


tensor([[0.0000, 0.0000, 0.0000, 0.0176, 0.0000, 0.0293, 0.0000, 0.0210, 0.0000,
         0.0000]], device='cuda:0', grad_fn=<ReluBackward0>)
Predicted class: tensor([5], device='cuda:0')


In [7]:
print(f"First Linear weights: {model.linear_relu_stack[0].weight} \n")
print(f"First Linear weights: {model.linear_relu_stack[0].bias} \n")

First Linear weights: Parameter containing:
tensor([[-0.0232, -0.0270,  0.0101,  ...,  0.0084, -0.0079, -0.0153],
        [ 0.0225, -0.0307,  0.0054,  ...,  0.0062,  0.0066, -0.0238],
        [ 0.0247, -0.0073,  0.0053,  ..., -0.0334,  0.0337,  0.0095],
        ...,
        [ 0.0226, -0.0103,  0.0150,  ...,  0.0011, -0.0202,  0.0245],
        [-0.0057, -0.0164,  0.0204,  ...,  0.0303,  0.0084,  0.0283],
        [-0.0310,  0.0225,  0.0231,  ...,  0.0224, -0.0160,  0.0248]],
       device='cuda:0', requires_grad=True) 

First Linear weights: Parameter containing:
tensor([ 0.0016, -0.0221, -0.0307,  0.0201, -0.0122, -0.0227, -0.0294,  0.0220,
        -0.0062, -0.0214, -0.0020, -0.0027, -0.0308,  0.0303, -0.0175,  0.0117,
        -0.0252, -0.0232,  0.0132, -0.0079, -0.0222, -0.0237,  0.0273,  0.0150,
         0.0238, -0.0355,  0.0247,  0.0101, -0.0166, -0.0107,  0.0062, -0.0173,
        -0.0283,  0.0224,  0.0329,  0.0119,  0.0085, -0.0222, -0.0289, -0.0078,
         0.0309,  0.0119, -0.008

In [9]:
# 准备一个小批量数据，查看每一层都做了什么
input_image = torch.rand(3, 28, 28)
print(input_image.size())

torch.Size([3, 28, 28])


In [10]:
# Flatten将2维数据转换为连续的一维数据
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [11]:
# Linear将输入数据做线性变换:weight * input + bias
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])
